import { Post } from "@/types/graphql";
import React from "react";
import ImageComponent from "../ImageComponent";
import Link from "next/link";
import parse from "html-react-parser";
import Icon from "../Icon";

import styles from "./PostCard.module.scss";
import DateFormated from "../DateFormated";
import ImageWithTexture from "../ImageWithTexture/Index";

/**
 * Type constraint for WordPress post types.
 * Works with any WordPress generated post type (Post, CaseStudy, or custom types).
 */
type WordPressPostType = Record<string, any> & {
  id?: string;
  databaseId?: number;
};

/**
 * Generic PostCard component that works with any WordPress post type.
 * Automatically compatible with all post types generated by GraphQL codegen.
 */
const PostCard = <T extends WordPressPostType = Post>({ post }: { post: T }) => {
  const { uri, title, featuredImage, excerpt, date, categories, author } = post;

  return (
    <Link className={styles.card} href={uri ?? ""}>
      {featuredImage && (
        <div className={styles["card__image"]}>
          <div className={styles["card__image-wrapper"]}>
            <ImageWithTexture image={featuredImage.node} />
          </div>
        </div>
      )}

      <div className={styles["card__content"]}>
        <div className={styles["card__content--category"]}>Blog</div>
        <div className={styles["card__content--header"]}>
          <h3>{title}</h3>
        </div>

        <span className={styles["card__arrow"]}>
          <Icon type="arrowRight" />
        </span>
      </div>
    </Link>
  );
};

export default PostCard;
