import { CaseStudy, Post } from "@/types/graphql";
import React from "react";
import ImageComponent from "../ImageComponent";
import Link from "next/link";
import parse from "html-react-parser";
import Icon from "../Icon";

import styles from "./PostCard.module.scss";
import DateFormated from "../DateFormated";
import ImageWithTexture from "../ImageWithTexture/Index";

/**
 * Type constraint for WordPress post types.
 * Works with any WordPress generated post type (Post, CaseStudy, or custom types).
 */
type WordPressPostType = Record<string, any> & {
  id?: string;
  databaseId?: number;
};

/**
 * Generic PostCard component that works with any WordPress post type.
 * Automatically compatible with all post types generated by GraphQL codegen.
 */
const PostCard = <T extends WordPressPostType = Post | CaseStudy>({ post }: { post: T }) => {
  const { uri, title, featuredImage, excerpt, date, categories, author } = post;

  return (
    <Link className={styles.card} href={uri ?? ""}>
      {/* {featuredImage && <ImageComponent image={featuredImage.node} />} */}
      <div className={styles["card__image"]}>
        <div className={styles["card__image-wrapper"]}>
          <ImageWithTexture />
        </div>

        <div className={styles["card__read-more"]}>
          <span className={styles["card__read-more-ellipse"]}></span>
          <span>Read More</span>
        </div>
      </div>

      <div className={styles["card__content"]}>
        <div className={styles["card__content--header"]}>
          <h3>{title}</h3>
          <span className={styles["card__content--date"]}>
            Published <DateFormated date={date} />
          </span>
        </div>

        <div className={styles["card__author"]}>
          <div className={styles["card__author-image"]}></div>
          <div className={styles["card__author-meta"]}>
            <span className={styles["card__author-name"]}>{author?.node.name}</span>
          </div>
        </div>
      </div>
    </Link>
  );
};

export default PostCard;
