"use client";

import { CaseStudy, Post } from "@/types/graphql";

import { useState, useMemo, useCallback, useEffect } from "react";
import Link from "next/link";
import Container from "../Container";

import styles from "./PostsList.module.scss";
import PostCard from "../PostCard";

const ITEMS_PER_PAGE = 6;

/**
 * Type constraint for WordPress post types.
 * Works with any WordPress generated post type (Post, CaseStudy, or custom types).
 * Uses Record<string, any> to allow any WordPress post type fields.
 */
type WordPressPostType = Record<string, any> & {
  id?: string;
  databaseId?: number;
};

// Utility function to strip HTML tags
const stripHtml = (html: string) => html.replace(/<[^>]*>/g, "");

// Debounce utility
function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState(value);

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedValue(value);
    }, delay);

    return () => {
      clearTimeout(handler);
    };
  }, [value, delay]);

  return debouncedValue;
}

type Category = {
  id?: number | string;
  name?: string;
  slug?: string;
  taxonomy?: string;
  url?: string;
};

interface PostsListProps<T extends WordPressPostType> {
  items: T[];
  itemsPerPage?: number;
  renderItem?: (item: T) => React.ReactNode;

  categories?: Category[];
}

/**
 * Generic PostsList component that works with any WordPress post type.
 * Automatically compatible with Post, CaseStudy, and any custom post types
 * generated by GraphQL codegen.
 */
function PostsList<T extends WordPressPostType = Post | CaseStudy>({
  items,
  itemsPerPage = ITEMS_PER_PAGE,
  renderItem,
  categories,
}: PostsListProps<T>) {
  const [searchInput, setSearchInput] = useState("");
  const [sortOrder, setSortOrder] = useState<"newest" | "oldest">("newest");
  const [currentPage, setCurrentPage] = useState(1);

  // Debounce search term to avoid filtering on every keystroke
  const searchTerm = useDebounce(searchInput, 300);

  // Filter and sort posts
  const filteredAndSorted = useMemo(() => {
    let filtered: T[] = items;

    // Search filter
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      filtered = items.filter((item) => {
        const title = item.title?.toLowerCase() || "";
        const excerpt = stripHtml(item.excerpt || "").toLowerCase();
        const content = stripHtml(item.content || "").toLowerCase();
        return title.includes(search) || excerpt.includes(search) || content.includes(search);
      });
    }

    // Sort by date (filtered is already a new array if search was applied)
    return filtered.sort((a, b) => {
      const dateA = a.date ? new Date(a.date).getTime() : 0;
      const dateB = b.date ? new Date(b.date).getTime() : 0;
      return sortOrder === "newest" ? dateB - dateA : dateA - dateB;
    });
  }, [items, searchTerm, sortOrder]);

  // Pagination
  const totalPages = Math.ceil(filteredAndSorted.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedItems = filteredAndSorted.slice(startIndex, startIndex + itemsPerPage);

  // Reset to page 1 when search or sort changes
  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, sortOrder]);

  const handleSort = useCallback((order: "newest" | "oldest") => {
    setSortOrder(order);
  }, []);

  return (
    <Container className={styles.posts}>
      <div className={styles["posts__actions"]}>
        <form className={styles["posts__actions-search"]} role="search" onSubmit={(e) => e.preventDefault()}>
          <label htmlFor="posts-search" className="visuallyhidden">
            Search
          </label>
          <input
            id="posts-search"
            type="search"
            placeholder="Search..."
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            aria-label="Search posts"
          />
          <button type="submit" aria-label="Submit search">
            search
          </button>
        </form>

        <div className={styles["posts__actions-sort"]}>
          <label className="visuallyhidden" htmlFor="sort-order">
            Sort by:
          </label>
          <div className={styles["select-wrapper"]}>
            <select
              id="sort-order"
              value={sortOrder}
              onChange={(e) => handleSort(e.target.value as "newest" | "oldest")}
            >
              <option value="newest">Newest</option>
              <option value="oldest">Oldest</option>
            </select>
          </div>
        </div>
      </div>

      {/* Categories: either render a provided React node (backwards compat)
          or render an array of category objects as links to category pages */}
      {categories && (
        <div className={styles["posts__categories"]}>
          {Array.isArray(categories) ? (
            <nav aria-label="Categories">
              <ul>
                {categories.map((cat) => {
                  const key = String(cat?.slug ?? cat?.id ?? cat?.name ?? "cat");
                  const url = String(cat?.url);
                  return (
                    <li key={key}>
                      <Link href={url}>{cat?.name ?? cat?.slug ?? cat?.id}</Link>
                    </li>
                  );
                })}
              </ul>
            </nav>
          ) : (
            categories
          )}
        </div>
      )}

      {filteredAndSorted.length === 0 ? (
        <div className={styles["posts__no-results"]}>
          <p>No posts found matching your search.</p>
        </div>
      ) : (
        <>
          <div className={styles["posts__list"]}>
            {paginatedItems.map((item) =>
              renderItem ? (
                <div key={item.databaseId ?? item.id ?? item.slug}>{renderItem(item)}</div>
              ) : (
                <PostCard key={item.databaseId ?? item.id ?? item.slug} post={item} />
              ),
            )}
          </div>

          {totalPages > 1 && (
            <nav className={styles["posts__pagination"]} aria-label="Posts pagination">
              <div className={styles["posts__pagination-pages"]}>
                {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                  <button
                    key={page}
                    onClick={() => setCurrentPage(page)}
                    className={currentPage === page ? styles.active : ""}
                    aria-label={`Go to page ${page}`}
                    aria-current={currentPage === page ? "page" : undefined}
                  >
                    {page}
                  </button>
                ))}
              </div>
            </nav>
          )}
        </>
      )}
    </Container>
  );
}

export default PostsList;
