import type { Metadata } from "next";
import "./styles/tailwind.css";
import "./styles/main.scss";

import Header from "./components/Header";
import Footer from "./components/Footer";
import { DM_Sans } from "next/font/google";
import GSAPProvider from "./components/GsapProvider";
import Banner from "./components/Banner";
import Script from "next/script";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={dmSans.variable} data-scroll-behavior="smooth">
      <body suppressHydrationWarning>
        <Script
          strategy="beforeInteractive"
          type="text/javascript"
          src="https://cdn-redirector.glopal.com/glopal-loader.js?glopal_store_id=esw"
        />
        <GSAPProvider />
        <Header />
        <main suppressHydrationWarning>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
