import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/main.scss";

import Header from "./components/Header";
import Footer from "./components/Footer";
import ScrollRestoration from "./components/ScrollRestoration";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const matter = localFont({
  src: [
    { path: "../public/fonts/Matter/Matter-TRIAL-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Matter/Matter-TRIAL-RegularItalic.woff2", weight: "400", style: "italic" },
    { path: "../public/fonts/Matter/Matter-TRIAL-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/Matter/Matter-TRIAL-MediumItalic.woff2", weight: "500", style: "italic" },
    { path: "../public/fonts/Matter/Matter-TRIAL-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/Matter/Matter-TRIAL-SemiBoldItalic.woff2", weight: "600", style: "italic" },
    { path: "../public/fonts/Matter/Matter-TRIAL-Bold.woff2", weight: "700", style: "normal" },
    { path: "../public/fonts/Matter/Matter-TRIAL-BoldItalic.woff2", weight: "700", style: "italic" },
    { path: "../public/fonts/Matter/Matter-TRIAL-Heavy.woff2", weight: "800", style: "normal" },
    { path: "../public/fonts/Matter/Matter-TRIAL-HeavyItalic.woff2", weight: "800", style: "italic" },
  ],
  variable: "--font-matter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body>
        {/* <Header /> */}

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
